import { DatabaseSync } from "node:sqlite";
import { mkdirSync } from "node:fs";
import path from "node:path";
import type { Opportunity } from "./opportunities";

const filename=process.env.DATABASE_FILE||(process.env.VERCEL?"/tmp/freelance-workbench.db":".data/freelance-workbench.db");
let connection:DatabaseSync|undefined;
function database(){if(connection)return connection;if(filename!==":memory:")mkdirSync(path.dirname(filename),{recursive:true});const db=new DatabaseSync(filename);db.exec(`PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS opportunities(id TEXT PRIMARY KEY,source_url TEXT UNIQUE NOT NULL,payload_json TEXT NOT NULL,last_seen_at TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS workspace_items(opportunity_id TEXT PRIMARY KEY,stage TEXT NOT NULL CHECK(stage IN ('saved','pipeline','applied','archived')),note TEXT NOT NULL DEFAULT '',draft TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL,FOREIGN KEY(opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS workspace_events(id INTEGER PRIMARY KEY AUTOINCREMENT,opportunity_id TEXT NOT NULL,event_type TEXT NOT NULL CHECK(event_type IN ('created','stage_changed','content_updated')),from_stage TEXT,to_stage TEXT NOT NULL,changed_at TEXT NOT NULL,FOREIGN KEY(opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS opportunities_active_seen ON opportunities(active,last_seen_at DESC);
CREATE INDEX IF NOT EXISTS workspace_events_changed ON workspace_events(changed_at DESC,id DESC);`);connection=db;return db}

export type WorkspaceStage="saved"|"pipeline"|"applied"|"archived";
export type WorkspaceEventType="created"|"stage_changed"|"content_updated";
export function saveSnapshot(items:Opportunity[]){const db=database(),now=new Date().toISOString(),ids=new Set(items.map(x=>x.id));const upsert=db.prepare(`INSERT INTO opportunities(id,source_url,payload_json,last_seen_at,active) VALUES(?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET source_url=excluded.source_url,payload_json=excluded.payload_json,last_seen_at=excluded.last_seen_at,active=1`);db.exec("BEGIN");try{for(const item of items)upsert.run(item.id,item.sourceUrl,JSON.stringify(item),now);for(const row of db.prepare("SELECT id FROM opportunities WHERE active=1").all() as{id:string}[])if(!ids.has(row.id))db.prepare("UPDATE opportunities SET active=0 WHERE id=?").run(row.id);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}}
export function listWorkspace(){const db=database();return(db.prepare(`SELECT w.opportunity_id,w.stage,w.note,w.draft,w.updated_at,o.payload_json,o.active FROM workspace_items w JOIN opportunities o ON o.id=w.opportunity_id ORDER BY w.updated_at DESC`).all() as any[]).map(row=>({opportunityId:row.opportunity_id,stage:row.stage,note:row.note,draft:row.draft,updatedAt:row.updated_at,opportunity:JSON.parse(row.payload_json),sourceStillActive:Boolean(row.active)}))}
export function listWorkspaceActivity(limit=50){const safeLimit=Math.max(1,Math.min(100,Math.trunc(limit)||50));return(database().prepare(`SELECT e.id,e.opportunity_id,e.event_type,e.from_stage,e.to_stage,e.changed_at,o.payload_json,o.active FROM workspace_events e JOIN opportunities o ON o.id=e.opportunity_id ORDER BY e.changed_at DESC,e.id DESC LIMIT ?`).all(safeLimit) as any[]).map(row=>{const opportunity=JSON.parse(row.payload_json) as Opportunity;return{id:Number(row.id),opportunityId:row.opportunity_id,eventType:row.event_type as WorkspaceEventType,fromStage:row.from_stage as WorkspaceStage|null,toStage:row.to_stage as WorkspaceStage,changedAt:row.changed_at,sourceStillActive:Boolean(row.active),opportunity:{company:opportunity.company,role:opportunity.role,source:opportunity.source,sourceUrl:opportunity.sourceUrl}}})}
export function updateWorkspace(input:{opportunityId:string;stage:WorkspaceStage;note?:string;draft?:string}){const db=database();if(!db.prepare("SELECT 1 FROM opportunities WHERE id=?").get(input.opportunityId))return null;const existing=db.prepare("SELECT stage,note,draft FROM workspace_items WHERE opportunity_id=?").get(input.opportunityId) as{stage:WorkspaceStage;note:string;draft:string}|undefined,now=new Date().toISOString(),note=input.note||"",draft=input.draft||"",eventType:WorkspaceEventType=!existing?"created":existing.stage!==input.stage?"stage_changed":"content_updated";db.exec("BEGIN");try{db.prepare(`INSERT INTO workspace_items(opportunity_id,stage,note,draft,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(opportunity_id) DO UPDATE SET stage=excluded.stage,note=excluded.note,draft=excluded.draft,updated_at=excluded.updated_at`).run(input.opportunityId,input.stage,note,draft,now);db.prepare("INSERT INTO workspace_events(opportunity_id,event_type,from_stage,to_stage,changed_at) VALUES(?,?,?,?,?)").run(input.opportunityId,eventType,existing?.stage??null,input.stage,now);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}return{...input,note,draft,updatedAt:now,eventType}}
export function storageInfo(){const db=database();const opportunities=db.prepare("SELECT COUNT(*) AS count FROM opportunities").get() as{count:number},workspace=db.prepare("SELECT COUNT(*) AS count FROM workspace_items").get() as{count:number},events=db.prepare("SELECT COUNT(*) AS count FROM workspace_events").get() as{count:number};return{engine:"sqlite",durable:!process.env.VERCEL&&filename!==":memory:",opportunityCount:Number(opportunities.count),workspaceCount:Number(workspace.count),workspaceEventCount:Number(events.count)}}
export function metricsSnapshot(){const db=database(),opportunityRows=db.prepare("SELECT active,COUNT(*) AS count FROM opportunities GROUP BY active").all() as{active:number;count:number}[],stageRows=db.prepare("SELECT stage,COUNT(*) AS count FROM workspace_items GROUP BY stage").all() as{stage:WorkspaceStage;count:number}[],eventCount=Number((db.prepare("SELECT COUNT(*) AS count FROM workspace_events").get() as{count:number}).count);const opportunities={active:0,inactive:0,total:0},stages:Record<WorkspaceStage,number>={saved:0,pipeline:0,applied:0,archived:0};for(const row of opportunityRows){const count=Number(row.count);opportunities[row.active?"active":"inactive"]+=count;opportunities.total+=count}for(const row of stageRows)stages[row.stage]=Number(row.count);return{durable:!process.env.VERCEL&&filename!==":memory:",opportunities,workspace:{total:Object.values(stages).reduce((sum,count)=>sum+count,0),stages,eventCount}}}
